### ISSUE TITLE
Wybór języka i narzędzi.

### ISSUE THREAD

**Issue by bix709** [bix709/ISI_Rejestracja_na_studia#1]
Musimy zdecydowac sie w czym robimy projekt. Język , baza danych.

**Comment by Looookiee** [comment]
PHP

**Comment by bix709** [comment]
Ja proponuje Python , i baze obojętnie, ale wygodniej będzie chyba Oracle :)

**Comment by Amicookie** [comment]
OK, jedna sprawa: ja nie miałam nigdy zajęć z Oracle, a MySQLa wszyscy znamy, więc uważam, że tak będzie łatwiej. 
Druga sprawa: nie wiem co zrobić z tym pythonem, bo go nie ogarniam i nigdy nie miałam z nim do czynienia, a nie mam zamiaru nie zdać tylko dlatego, że językiem jest coś czego nie znam...

**Comment by bix709** [comment]
Spoko, moze być MySQL, zadna roznica to jest bo zapytania i tak sa w SQL. Czemu mamy nie zdac ? Zdamy to ,PHP umiecie tylko wy we dwie, my tez nie ogarniamy tego, także tak czy siak ktoś by musiał poswięcic się, a jako że zawsze są rzeczy do roboty poza pythonem ,jak baza i front-end to mozna ta prace podzielic. Mysle że mimo wszystko zdecydowanie lepiej jest robic to w pythonie bo ma tam biblioteki doslownie do wszystkiego , pozatym jest duzo bardziej potrzebny na rynku pracy, wiec napewno sie nam wszystkim przyda :P Natomiast no nie bede rządził , jak sie nie okreslimy to mozna zrobic glosowanie albo coś , takze decydujcie :)
